name: Trigger auto deployment for ansalemo-cicd-aca-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ansalemo-cicd-aca-test-AutoDeployTrigger-e21a43e6-eb64-43b8-9c8a-76c0f159ce6c.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOCICDACATEST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ansalemoacr.azurecr.io
          registryUsername: ${{ secrets.ANSALEMOCICDACATEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANSALEMOCICDACATEST_REGISTRY_PASSWORD }}
          containerAppName: ansalemo-cicd-aca-test
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: ansalemoacr.azurecr.io/ansalemo-cicd-aca-test:${{ github.sha }}
          

     

